name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: |
        # Kill any existing bot process
        if [ -f bot.pid ]; then
          kill $(cat bot.pid) 2>/dev/null || true
          rm bot.pid
        fi
        
        # Start the bot
        python main.py > bot.log 2>&1 &
        echo $! > bot.pid
        
        # Wait and check if the bot is running
        sleep 10
        if ! ps -p $(cat bot.pid) > /dev/null; then
          echo "Bot failed to start. Showing logs:"
          cat bot.log
          exit 1
        fi
        
        # Show the last 50 lines of the log
        echo "Bot started successfully. Showing recent logs:"
        tail -n 50 bot.log 